# ==================== 全局配置 ====================
SIGN_CONST = "P.8CGq@Wr~Vs]!4!"
API_LEVEL = "36"
LIMIT = "50"
BASE_URL = "https://rtkapi2.ruansky.net"
CHANNEL = "rtk"
USER_AGENT = "Dalvik/2.1.0 (Linux; U; Android 12; JLH-AN00 Build/HONORJLH-AN00)"
VERSION = "8740"
PHONE_MODEL = ""
REQUEST_DELAY_MS = 10
OS_INFO = ""
PAGE = "1"
# 全局正则开关
ENABLE_REGEX = true
CHECK_INTERVAL_SECONDS = 50
CONCURRENCY = 8
# 界面主题: tokyo-night / dark / light
THEME = "tokyo-night"

# ==================== Token 配置 ====================
[[TOKENS]]
# 可选：覆盖违禁词开关
ENABLE_BADWORDS = true
# 可选：覆盖全局正则开关
ENABLE_REGEX = true
UID = "552141"
# 可选：覆盖全局并发数
CONCURRENCY = 8
# 可选：覆盖全局请求延迟
REQUEST_DELAY_MS = 25
TOKEN = ""

[[TOKENS.FAMILIES]]
FAMILY_ID = ""
ENABLE_POST = true
ENABLE_COMMENT = true
ENABLE_JOIN = false
MID = ""
ENABLE_UP = true
MIN_LEVEL = -1

[[TOKENS.FAMILIES]]
MIN_LEVEL = -1
ENABLE_UP = false
MID = ""
ENABLE_JOIN = false
ENABLE_COMMENT = true
ENABLE_POST = true
FAMILY_ID = ""


[[TOKENS]]
TOKEN = ""
UID = ""
# 可选：覆盖全局正则开关
ENABLE_REGEX = true
# 可选：覆盖违禁词开关
ENABLE_BADWORDS = true

[[TOKENS.FAMILIES]]
MIN_LEVEL = -1
ENABLE_UP = false
MID = ""
ENABLE_JOIN = false
ENABLE_COMMENT = true
ENABLE_POST = true
FAMILY_ID = ""

#之后可任意增加
# ==================== 审核模块接口配置 ====================
[JOIN]
ENABLED = true
LIST_ENDPOINT = "/family/join/user-list"
OPERATE_ENDPOINT = "/family/join/user-result"
STATE3_PENDING = "1"
STATE3_APPROVED = "3"
STATE3_REJECTED = "2"
[UP]
ENABLED = true
LIST_ENDPOINT = "/family/up/check-comment/list"
OPERATE_ENDPOINT = "/family/up/check-comment/operate"
STATE3_PENDING = "1"
STATE3_APPROVED = "3"
STATE3_REJECTED = "2"
[POST]
ENABLED = true
LIST_ENDPOINT = "/family/bbs/check/list"
OPERATE_ENDPOINT = "/family/bbs/check/operate"
STATE3_PENDING = "1"
STATE3_APPROVED = "3"
STATE3_REJECTED = "2"
[COMMENT]
ENABLED = true
LIST_ENDPOINT = "/family/bbs/check-comment/list"
OPERATE_ENDPOINT = "/family/bbs/check-comment/operate"
STATE3_PENDING = "1"
STATE3_APPROVED = "3"
STATE3_REJECTED = "2"

